TextIntentProject/api/urls.py
from django.urls import path

from .ninja_api import api as ninja_api

app_name = "api"

urlpatterns = [
    path('', ninja_api.urls)
]

TextIntentProject/core/urls.py
from django.urls import path, include
from .views import (
    HomeView, 
    CheckIntent, 
    TextTrainData, 
    )
app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('check-intent/', CheckIntent.as_view(), name='check_intent'),

    path('train-data/', TextTrainData.as_view(), name='text_train_data'),
    path('train-data/<pk>/', TextTrainData.as_view(), name='single_text_train_data'),
]

TextIntentProject/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>  
	<script>
		setTimeout(function() {
			bootstrap.Alert.getOrCreateInstance(document.querySelector(".alert")).close();
		}, 2500)
	</script>
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

	{% block extracss %}{% endblock extracss %}
</head>
<body  class="bg-dark">
	   
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	<div class="container-fluid">
	  <a class="navbar-brand mx-4" href="/">Text Intent</a>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
		  <li class="nav-item">
			<a class="nav-link text-white" href="{% url 'core:check_intent' %}">Check Intent</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link text-white" href="{% url 'core:text_train_data' %}">Train Data</a>
		  </li>
		</ul>
	  </div>
	</div>
  </nav>
  <br><br>
  <main class="container mt-4 ">
		
		{% block content %}{% endblock content %}
		{% if messages %}
		<div class="container row col-8 offset-2 mt-4">
			{% for message in messages %}
				{% if forloop.last %}
				<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
					<span class="fw-medium">Info:</span> {{message}}
				</div>
				{% endif %}
			{% endfor %}
		</div>
		{% endif %}
  </main>

    {% block extrajs %}
	{% endblock extrajs %}
  </body>
</html>