TextIntentProject/api/urls.py
from django.urls import path

from .ninja_api import api as ninja_api

app_name = "api"

urlpatterns = [
    path('', ninja_api.urls)
]

TextIntentProject/core/urls.py
from django.urls import path, include
from .views import (
    HomeView, 
    CheckIntent, 
    TextTrainData, 
    )
app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('check-intent/', CheckIntent.as_view(), name='check_intent'),

    path('train-data/', TextTrainData.as_view(), name='text_train_data'),
    path('train-data/<pk>/', TextTrainData.as_view(), name='single_text_train_data'),
]

TextIntentProject/core/models.py
from django.db import models

# Create your models here.

TextIntentProject/core/views.py
#django Imports 
from django.shortcuts import redirect, render
from django.views.generic import View
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, StreamingHttpResponse, FileResponse, Http404
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.db.models import F
from django.utils.html import format_html
UserModel = get_user_model()
from django.db.models import Q


from django.shortcuts import render
from django.views.generic import TemplateView

    
from intents_app.models import TextIntent 
from utils.intents_app.handle_prediction import AiTextIntentPredictionModel
from utils.intents_app.handle_google_sheets import add_text

class HomeView(View):
    template_name = "core/home.html"
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class CheckIntent(View):
    template_name = "core/check_intent.html"
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        texts_list = self.request.POST.get('text_intent').split('\n')
        if len(texts_list) < 0 or len(texts_list) > 100:
            messages.info(request, f'List should be greater than 0 and up to 100')
            return redirect('core:text_intent_method_1')
                
        final_data = []
        for text in texts_list:
            text_data = str(text).lower()
            intent_result = AiTextIntentPredictionModel().getPrediction(text_data)
            final_data.append(intent_result)
        context = {
            'show_result' : True,
            'records': final_data, 
        }
        return render(request, self.template_name, context)
    
    
    
class TextTrainData(LoginRequiredMixin, View):
    template_name = "core/train.html"
    def get(self, request, *args, **kwargs):
        print("====")
        pk_ = kwargs.get('pk', None)
        print("pk_",pk_)
        if pk_:
            text_obj = TextIntent.objects.filter(id=pk_).first()
            print(text_obj)
        else:
            text_obj = TextIntent.objects.filter(intent=TextIntent.TEXT_INTENT.NOTSET).order_by('pk').first()
        if text_obj:
            already_trained = False
            if text_obj.intent in [TextIntent.TEXT_INTENT.INTERESTED_GENERAL, TextIntent.TEXT_INTENT.Neutral]:
                already_trained = True
            pre_guess_intent_result =  AiTextIntentPredictionModel().getOnlyIntent(str(text_obj.text).lower())
            context = {
                'text_obj':text_obj,
                'pre_guess_intent_result':pre_guess_intent_result,
                'previous_post_id': text_obj.id - 1,
                'next_post_id': text_obj.id + 1,
                'already_trained': already_trained
            }
            return render(request, self.template_name, context)
        messages.info(request, 'All texts are trained.')
        return redirect('core:check_intent')
    
    
    def post(self, request, *args, **kwargs):
        current_user = request.user
        text = str(self.request.POST.get('text_intent')).strip()
        text_uid = str(self.request.POST.get('text_uid')).strip()
        intent_options = self.request.POST.get('intent_options')
        object_ = TextIntent.objects.get(uid=text_uid)
        object_.text=text
        object_.intent=intent_options
        object_.is_approved=True
        if intent_options == 'opt_out':
            object_.intent = "skiped"
            object_.is_approved = False
            add_text(text)
        # if current_user.is_superuser:
        object_.save()            
        messages.info(request, 'Text has been Trained and saved into Database')
        return redirect('core:text_train_data')
    
    

TextIntentProject/templates/core/check_intent.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center ">
      <div class="col-lg-9 col-md-9 col-sm-11">
        <div class="card border-0 shadow-lg ">
          <div class="card-body py-1 px-1 px-sm-1">
            <h2 class="h3 text-center">Quick Check List (up to 100 Lines) | Lines: <span id="ncount"><strong>0</strong></span></h2>
            <form class="p-2" method="POST" action="." >
              {% csrf_token %}
              <div >
                  <textarea class="form-control" required name="text_intent" id="text_intent" rows="5" placeholder="One Message Per Line" ></textarea>
              </div>
              <div class="text-center">
                <button type="submit"  class="mt-2 btn btn-ld btn-primary text-center px-5" id="submit_btn_process">Get Intent</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>


{% if show_result %}
<div class="container my-5 ">
  <div class="row col-12">
    <h4 class="text-white">Results <small><a  href="#" onclick="export2csv()">(Export to CSV)</a></small></h4> 
      <div class="table-responsive">
        <table class="table text-white">
          <thead>
            <tr>
              <th>Sr</th>
              <th>Text</th>
              <th>Intent</th>
            </tr>
          </thead>
          <tbody>
            {% for record in records %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{record.Text}}</td>
                    <td>{{record.Intent}}</td>
                </tr> 
           {% empty %}
                <tr>
                  <th colspan=3>No Record Found</th>
                </tr>
           {% endfor %}
          </tbody>
        </table>
      </div>
  </div>
</div>
{% endif %}

{% endblock content %}

{% block extrajs %}
<script type="text/javascript">
    var btn_evnt = document.getElementById('submit_btn_process');
    btn_evnt.addEventListener('click', function () {
      if(document.getElementById("text_intent").value !=''){
        btn_evnt.innerHTML = "Checking.....";
      }
    });
</script>

<script>
var textArea = document.getElementById("text_intent");
var ncount = document.getElementById("ncount");

textArea.addEventListener("keypress", function () {
    var data = textArea.value
    if (data.value !== ''){
        data = data.split(/\r?\n/);
        var cleaned = data.filter(n => n);
        len = cleaned.length;
        ncount.innerHTML = "<strong>" +len+ "</strong>";
    }
    else{
        ncount.innerHTML = "<strong>" +0+ "</strong>";
    }
  
});


if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
</script>



<script>
    function export2csv() {
      let data = "";
      const tableData = [];
      const rows = document.querySelectorAll("table tr");
      for (const row of rows) {
        const rowData = [];
        for (const [index, column] of row.querySelectorAll("th, td").entries()) {
          // To retain the commas in the "Description" column, we can enclose those fields in quotation marks.
          if ((index + 1) % 3 === 0) {
            rowData.push('"' + column.innerText + '"');
          } else {
            rowData.push(column.innerText);
          }
        }
        tableData.push(rowData.join(","));
      }
      data += tableData.join("\n");
      const a = document.createElement("a");
      a.href = URL.createObjectURL(new Blob([data], { type: "text/csv" }));
      a.setAttribute("download", "TextIntentOutputFile.csv");
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    }
  </script>

{% endblock extrajs %}

TextIntentProject/templates/core/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block content %}


{% endblock content %}

TextIntentProject/templates/core/train.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block extracss %}
<style>
  .supclass {
    top: -1rem;
    left: -0.5rem;
    color: #666666;
    font-size: 14px;
}
    /* This hides the default radio buttons */
    [type="checkbox"]:checked,
    [type="checkbox"]:not(:checked),
    [type="radio"]:checked,
    [type="radio"]:not(:checked){
        position: absolute;
        left: -9999px;
        width: 0;
        height: 0;
        visibility: hidden;
    }
    
    [type="radio"]:checked,
    [type="radio"]:not(:checked) {
      position: relative;
      left: 14px;
      z-index: 99;
    }
    
    .checkbox-tools:checked + label,
    .checkbox-tools:not(:checked) + label {
        margin-right: 10px;
        position: relative;
        display: inline-block;
        padding: 20px 20px 20px 20px;
        font-size: 14px;
        letter-spacing: 0px;
        text-align: left;
        border-radius: 4px;
        text-transform: uppercase;
        color: black;
        -webkit-transition: box-shadow 150ms ease;
        transition: box-shadow 150ms ease;
        left: 5%;
    }
    
    {% comment %} .checkbox-tools:checked + label {
        background-color: #080808;
        border: 2px solid #fffbfb;
        color: #fff;
        /* box-shadow: 0 8px 16px 0 rgb(0 0 0 / 20%); */
        box-shadow: 0 2px 4px 0 rgb(255 251 251 / 20%);
    } {% endcomment %}

    .checkbox-tools:checked + label {
      background-color: #080808;
      border: 2px solid #525252;
      color: #6c6c6c;
      /* box-shadow: 0 8px 16px 0 rgb(0 0 0 / 20%); */
      box-shadow: 0 2px 4px 0 rgb(255 251 251 / 20%);
  }

    
    .checkbox-tools:not(:checked) + label {
      background-color: #423e3e;
      border: 1px solid transparent;
      box-shadow: 0 2px 4px 0 rgb(0 0 0 / 20%);
      color: #858585;
  }
    
    .checkbox-tools:not(:checked) + label:hover,
    .checkbox-tools:checked + label:hover,
    [type="radio"]:hover + label {
      box-shadow: 0 8px 12px 0 rgba(0, 0, 0, 0.2);
      cursor: pointer;
      -webkit-transition: box-shadow 300ms ease;
      transition: box-shadow 300ms ease;
    }



    .form-control-2 {
      display: block;
      width: 100%;
      padding: 0.375rem 0.75rem;
      font-size: 1rem;
      font-weight: 400;
      line-height: -9.5;
      color: #9d9d9d;
      background-color: #585555;
      background-clip: padding-box;
      border: 2px solid #525354;
      -webkit-appearance: none;
      -moz-appearance: none;
      appearance: none;
      border-radius: 0.25rem;
      transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  }

  .btn-dark-2 {
    color: #666;
    background-color: #323232;
    border-color: #303030;
}
</style>
{% endblock extracss %}

{% block content %}
<div class="container">
    <div class="row justify-content-center my-5">
      <div class="col-lg-9 col-md-9 col-sm-11">
        <div class="card border-0 shadow-lg " style="
        background-color: #525050;
        color: gray;
    ">
          <div class="card-body py-1 px-1 px-sm-1">
            <h2 class="h3 text-center my-3">Train Text | ID {{text_obj.pk}} | Intent Guess: {{pre_guess_intent_result|title }} <br>
               {% if already_trained %} Already Saved with Intent: {{text_obj.get_intent_display}}{% endif %}</h2>
            <form class="p-2" method="POST" action="." id="trainForm">
                <input type="hidden" name="text_uid" value="{{text_obj.uid}}">
              {% csrf_token %}
                <div >
                    <textarea class="form-control form-control-2" required name="text_intent" id="text_intent" rows="4" placeholder="One Message Per Line" >{{text_obj.text}}</textarea>
                </div>
                <div class="container my-4">
                    <input class="checkbox-tools" type="radio" name="intent_options" id="interested_general" value="interested_general" {% if pre_guess_intent_result == 'interested_general' %} checked {% endif %} onclick="this.form.submit()">
                    <label for="interested_general"><sup class="supclass">1</sup> Interested General</label>
                    <input class="checkbox-tools" type="radio" name="intent_options" id="neutral" value="neutral" {% if pre_guess_intent_result == 'neutral' %} checked {% endif %} onclick="this.form.submit()">
                    <label for="neutral"><sup class="supclass">2</sup> Neutral</label>
                    <input class="checkbox-tools" type="radio" name="intent_options" id="opt_out" value="opt_out" onclick="this.form.submit()">
                    <label for="opt_out"><sup class="supclass">3</sup> OptOut</label>
                    <input class="checkbox-tools" type="radio" name="intent_options" id="skip" value="skiped" onclick="this.form.submit()">
                    <label for="skip"><sup class="supclass">4</sup> Skip</label>
                </div>
                
            </form>

          </div>
        </div>
      </div>
    </div>
    <div class="row col-6 offset-3">
      <a  href="{% url 'core:single_text_train_data' previous_post_id %}" class="col btn btn-dark-2 mx-4">Previous</a>
      <a  href="{% url 'core:single_text_train_data' next_post_id %}" class="col btn btn-dark-2">Next</a>
    </div>
  </div>

{% endblock content %}

{% block extrajs %}
<script type="text/javascript">
    var btn_evnt = document.getElementById('submit_btn_process');
    btn_evnt.addEventListener('click', function () {
      if(document.getElementById("text_intent").value !=''){
        btn_evnt.innerHTML = "Training.....";
      }
    });
</script>

<script>

if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
</script>

<script>
  document.addEventListener('keypress', (event) => {
    if(event.key && event.key   == 'Enter'){
      document.getElementById("trainForm").submit();
    }

    if(event.key && event.key == '1'){
      document.getElementById("interested_general").checked = true;
    }
    else if (event.key && event.key == '2'){
      document.getElementById("neutral").checked = true;

    }
    else if (event.key && event.key == '3'){
      document.getElementById("opt_out").checked = true;

    }
   
    else if (event.key && event.key == '4'){
      document.getElementById("skip").checked = true;

    }
   
});

</script>


{% endblock extrajs %}